Part 1 - Numpy

In [6]:
import numpy as np

In [7]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

1.⁠ ⁠Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

In [8]:
# Define arrays A and B
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]])

# Stack A and B vertically
vertical_stack = np.vstack((A, B))
print("Vertically Stacked Array:\n", vertical_stack)

# Stack A and B horizontally
horizontal_stack = np.hstack((A, B))
print("Horizontally Stacked Array:\n", horizontal_stack)

Vertically Stacked Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Horizontally Stacked Array:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


2. Find common elements between A and B

In [15]:
# Define NumPy arrays A and B
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[4, 5, 9], [2, 3, 12]])

common_elements = np.intersect1d(A, B)

print("Common Elements between A and B:", common_elements)

Common Elements between A and B: [2 3 4 5]


3.⁠ ⁠Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]

In [16]:
A = np.array([1, 3, 5, 7, 9, 11, 13])

min_val, max_val = 5, 10 

filtered_elements = A[(A >= min_val) & (A <= max_val)]

print("Numbers in A between 5 and 10:", filtered_elements)

Numbers in A between 5 and 10: [5 7 9]


4.⁠ ⁠Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

filtered_iris = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]
print("Filtered rows from iris_2d:\n", filtered_iris)

Part 2 - Pandas

In [1]:
import pandas as pd

1.⁠ ⁠From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [3]:
filtered_df = df.iloc[::20, :][['Manufacturer', 'Model', 'Type']]
print(filtered_df)

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


2.⁠ ⁠Replace missing values in Min.Price and Max.Price columns with their respective mean.

In [6]:
df.loc[:, 'Min.Price'] = df['Min.Price'].fillna(df['Min.Price'].mean())
df.loc[:, 'Max.Price'] = df['Max.Price'].fillna(df['Max.Price'].mean())

print(df[['Min.Price', 'Max.Price']].head())

   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091


3. Get the rows of a dataframe where row sum > 100

In [11]:
# Create a DataFrame with random integers between 10 and 40
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

# Select rows where row sum > 100
filtered_rows = df[df.sum(axis=1) > 100]

# Display the DataFrame
display(filtered_rows)

0   1   2   3
1   23  39  39  18
3   28  38  14  23
4   24  24  38  33
6   10  37  29  26
8   22  15  38  31
9   19  24  29  37
10  22  35  19  25
13  30  24  35  18
14  37  12  38  23